# Generated by Django 4.0.2 on 2022-02-19 07:46

from django.db import migrations, models
import massassi.models


class Migration(migrations.Migration):

    dependencies = [
        ('saberworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=massassi.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=massassi.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=massassi.models.get_image_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=massassi.models.get_image_upload_to),
        ),
    ]
