# Generated by Django 4.0.2 on 2022-02-22 18:36

from django.db import migrations, models
import saberworks.models


class Migration(migrations.Migration):

    dependencies = [
        ('saberworks', '0002_alter_file_image_alter_game_image_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
