# Generated by Django 4.0.2 on 2022-03-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saberworks', '0003_alter_project_image_alter_project_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='games',
            field=models.ManyToManyField(blank=True, to='saberworks.Game'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='saberworks.Tag'),
        ),
    ]
