# Generated by Django 4.0.2 on 2022-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saberworks', '0005_alter_post_text_screenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='Unknown', max_length=256),
            preserve_default=False,
        ),
    ]
