# Generated by Django 3.1.7 on 2021-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SotD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotd_date', models.DateField()),
                ('admin_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('author_email', models.EmailField(max_length=254, null=True)),
                ('url', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='sotd')),
            ],
            options={
                'verbose_name': 'Screenshot of the Day',
                'verbose_name_plural': 'Screenshots of the Day',
            },
        ),
    ]
