# Generated by Django 3.1.7 on 2021-03-24 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import levels.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('filesize', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dl_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('rate_count', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('file', models.FileField(null=True, upload_to=levels.util.get_level_upload_path)),
                ('screenshot_1', models.ImageField(null=True, upload_to=levels.util.get_screenshot_1_upload_path)),
                ('screenshot_2', models.ImageField(null=True, upload_to=levels.util.get_screenshot_2_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='LevelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('enable_3dpreview', models.BooleanField(default=False)),
                ('game', models.CharField(max_length=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'Level Categories',
            },
        ),
        migrations.CreateModel(
            name='LevelRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('rating', models.PositiveSmallIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelcategory'),
        ),
    ]
