# Generated by Django 3.1.7 on 2021-03-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('enable_3dpreview', models.BooleanField(default=False)),
            ],
        ),
    ]
