# Generated by Django 4.1.2 on 2022-11-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelcomment',
            options={'verbose_name_plural': 'Level Comments'},
        ),
    ]
