# Generated by Django 3.1.7 on 2021-03-21 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import levels.models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_auto_20210321_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('filename', models.CharField(max_length=128)),
                ('filesize', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('dl_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('rate_count', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('file', models.FileField(upload_to=levels.models.get_upload_path)),
                ('screenshot_1', models.ImageField(null=True, upload_to='levels/screenshots')),
                ('screenshot_2', models.ImageField(null=True, upload_to='levels/screenshots')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.levelcategory')),
            ],
        ),
    ]
