# Generated by Django 3.1.7 on 2021-03-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='filename',
        ),
    ]
