# Generated by Django 3.2.10 on 2022-01-03 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import holiday.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=32)),
                ('year', models.PositiveSmallIntegerField()),
                ('logo', models.ImageField(upload_to=holiday.models.get_holiday_upload_path)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_in_rotation', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Holiday Logos',
                'db_table': 'holiday_logos',
            },
        ),
        migrations.AddIndex(
            model_name='holidaylogo',
            index=models.Index(fields=['is_in_rotation'], name='holiday_log_is_in_r_bcfc67_idx'),
        ),
    ]
